baseurl = "https://tech.vertalo.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Vertalo"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-114921168-8"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "We build amazing software in Austin, Texas"
  mainSections = []
  logo = "http://app.vertalo.com/content/logos/color-bug" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  answerEmail = "hiring-tech@vertalo.com"
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Vertalo Earth HQ"
  website = "www.vertalo.com"
  email = "info@vertalo.com"
  facebook = "Vertalo-413757739053125"
  github = "Vertalo"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "Vertalo_"
  #reddit = "username"
  linkedin = "company/vertalo"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  youtube = "channel/UCvUAhmX0cqgvhUmNzZo0c5Q" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  telegram = "vertalotoken"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  medium = "vertalo"

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 2

[[menu.main]]
    name = "Careers"
    url = "careers/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 4

[[menu.main]]
    name = "Vertalo Home"
    url = "https://www.vertalo.com/"
    weight = 5


[taxonomies]
    tag = "tags"
